name: Norne

flownet:
  data_source:
    simulation:
      input_case: ../input_model/norne/NORNE_ATW2013
      vectors:
        WBHP:
          rel_error: 0.05
          min_error: 10
        WOPR:
          rel_error: 0.1
          min_error: 100
        WGPR:
          rel_error: 0.1
          min_error: 100000
      well_logs: true
      layers:
        - [1, 4]
        - [5, 22]
    concave_hull: true
  constraining:
    kriging:
      enabled: false
      n: 20
      n_lags: 6
      anisotropy_scaling_z: 10
      variogram_model: spherical
      permeability_variogram_parameters:
        sill: 0.75
        range: 1000
        nugget: 0
      porosity_variogram_parameters:
        sill: 0.05
        range: 1000
        nugget: 0
  phases:
    - oil
    - gas
    - vapoil
    - disgas
    - water
  pvt:
    rsvd: norne_static/rsvd_multiple.csv
  cell_length: 100
  additional_flow_nodes: [50, 200]
  additional_node_candidates: 10000
  hull_factor: 1.2
  random_seed: 123456
  perforation_handling_strategy: multiple_based_on_workovers
  mitchells_algorithm: fast
  fast_pyscal: true
  training_set_end_date: 2005-01-31
  fault_tolerance: 0.0001
  #max_distance_fraction: 0.10
  prod_control_mode: RESV
  inj_control_mode: RATE
  prior_volume_distribution: voronoi_per_tube
  place_nodes_in_volume_reservoir: true

ert:
  static_include_files: ./norne_static
  realizations:
    num_realizations: 250
    required_success_percent: 20
    max_runtime: 500
  queue:
    system: LOCAL
    max_running: 20
  ensemble_weights:
    - 4
    - 2
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1

model_parameters:
  permeability:
    mean: 390
    max: 2000
    distribution: logunif
  porosity:
    mean: 0.24
    stddev: 0.02
    distribution: normal
  bulkvolume_mult:
    mean: 1.0
    max: 2
  fault_mult:
    min: 0.0001
    max: 1
    distribution: uniform
  relative_permeability:
    scheme: individual
    interpolate: false
    regions:
      - id: None
        swirr:
          min: 0.01
          base: 0.01
          max: 0.01
        swl:
          min: 0.05
          base: 0.05
          max: 0.05
        swcr:
          min: 0.1
          base: 0.2
          max: 0.3
        sorw:
          min: 0.2
          base: 0.25
          max: 0.3
        sorg:
          min: 0.1
          base: 0.15
          max: 0.2
        sgcr:
          min: 0.03
          base: 0.055
          max: 0.08
        krwend:
          min: 0.4
          base: 0.5
          max: 0.6
        kroend:
          min: 0.9
          base: 0.95
          max: 1.0
        krgend:
          min: 0.9
          base: 0.95
          max: 1.0
        nw:
          min: 1.5
          base: 2.25
          max: 3.0
        now:
          min: 1.5
          base: 2.25
          max: 3.0
        ng:
          min: 1.5
          base: 2.25
          max: 3.0
        nog:
          min: 1.5
          base: 2.25
          max: 3.0

  equil:
    scheme: regions_from_sim
    regions:
      - id: 1
        datum_depth: 2582
        datum_pressure:
          min: 268.4
          max: 268.5
        goc_depth:
          min: 2579
          max: 2585
        owc_depth:
          min: 2689
          max: 2695
      - id: 2
        datum_depth: 2500
        datum_pressure:
          min: 263.4
          max: 263.5
        goc_depth:
          min: 2497
          max: 2503
        owc_depth:
          min: 2582
          max: 2588
      - id: 3
        datum_depth: 2582
        datum_pressure:
          min: 269.4
          max: 269.5
        goc_depth:
          min: 2579
          max: 2585
        owc_depth:
          min: 2615
          max: 2621
      - id: 4
        datum_depth: 2200
        datum_pressure:
          min: 236.9
          max: 237.0
        goc_depth:
          min: 2197
          max: 2203
        owc_depth:
          min: 2397
          max: 2403
      - id: 5
        datum_depth: 2585
        datum_pressure:
          min: 268.7
          max: 268.8
        goc_depth:
          min: 2582
          max: 2588
        owc_depth:
          min: 2690
          max: 2696
