name: Norne

flownet:
  data_source:
    input_case: ../input_model/norne/NORNE_ATW2013
    concave_hull: True
  phases:
    - oil
    - gas
    - vapoil
    - disgas
    - water
  pvt:
    rsvd: norne_static/rsvd.csv
  cell_length: 100
  additional_flow_nodes: 50
  additional_node_candidates: 1000
  hull_factor: 1.2
  random_seed: 123456
  perforation_handling_strategy: bottom_point
  fast_pyscal: True
  training_set_end_date: 2005-01-31 #YYYY-MM-DD. If defined training set fraction is calculated from this date
  fault_tolerance: 0.00001
  max_distance_fraction: 0.15

ert:
  static_include_files: ./norne_static
  realizations:
    num_realizations: 200
    required_success_percent: 20
    max_runtime: 600   # Maximum runtime of on single realization in seconds
  queue:
    system: LOCAL   # LOCAL or LSF
    max_running: 5   # Maximum number of simultaneous runs
  ensemble_weights:
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1

model_parameters:
  permeability:
    mean: 390
    max: 4000
  porosity:
    mean: 0.25
    max: 0.35
  bulkvolume_mult:
    min: 1
    max: 4
  fault_mult:
    min: 0.0001
    max: 1
    loguniform: True
  relative_permeability:
    scheme: global
    swirr:
      min: 0.01
      max: 0.04
    swl:
      min: 0.05
      max: 0.07
    swcr:
      min: 0.08
      max: 0.15
    sorw:
      min: 0.2
      max: 0.3
    sorg:
      min: 0.05
      max: 0.1
    sgcr:
      min: 0.01
      max: 0.05
    krwend:
      min: 0.4
      max: 0.6
    krowend:
      min: 0.9
      max: 1.0
    krgend:
      min: 0.9
      max: 1.0
    krogend:
      min: 0.9
      max: 1.0
    nw:
      min: 0.5
      max: 2.5
    now:
      min: 0.5
      max: 2.5
    ng:
      min: 0.5
      max: 2.5
    nog:
      min: 0.5
      max: 2.5
  equil:
    scheme: individual
    datum_pressure:
      min: 250
      max: 275
    owc_depth:
      min: 2675
      max: 2725
    goc_depth:
      min: 2575
      max: 2600
